# Override tmux colour settings
set-option -sa terminal-overrides ",xterm*:Tc"

# General config
set -g prefix2 C-\\
set -s escape-time 0
set -g mode-keys vi
set -g status-keys vi
set -g allow-rename off

# Bindings
bind C-s choose-tree -ZsN
bind s split-window
unbind '"'
bind v split-window -h
unbind %
bind w choose-tree -ZN

# Spawn ranger with prefix-e
bind e split-window -h bash -ilc ranger

# Copying to xclip clipboard
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Easy pane switching
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind -n M-\; last-pane
bind -n M-\: command-prompt
bind -n M-n next-window
bind -n M-p previous-window
bind -n M-, command-prompt -I "#W" { rename-window "%%" }
bind -n M-< command-prompt -I "#S" { rename-session "%%" }
bind -n M-[ copy-mode
bind -n M-] paste-buffer -p

# M-z toggle status
bind -n M-z set -g status

# M-w choose window
bind -n M-w choose-tree -ZN

# Status config
set -g status-position bottom
set -g status-style 'fg=white bg=default'
set -g status-left " #S#[fg=#505762]:"
set -g status-right " #(~/scripts/get_mpris_media_playing.sh --limit 50) #[fg=#505762]|#[fg=white] #(~/.config/tmux/status.sh) #[fg=#505762]|#[fg=white] %H:%M %b %-d "
set -g status-right-length 100
set -g status-interval 5

# Message config
set -g message-style 'fg=black bg=white'
set -g message-command-style 'fg=black bg=white'

# Window status config
setw -g window-status-current-format ' #W#[fg=#505762]#F '
setw -g window-status-format ' #[fg=#505762]#W#F '
